### PR TITLE
clean up team db after test session run

### PR DESCRIPTION
**Pull request by jeffreyguo**
Added dropDatabase() to clean up temp database at the end of Behat test session.

### CODE REVIEW

**Comment by dhensby** [comment]
rebase, please

**Comment by jeffreyguo** [comment]
@dhensby : it is already based on the latest master [cedb6e2].

**Comment by dhensby** [comment]
the latest master is 5167be8d96ad4561a16e0080637293ee354125dc

I can't merge it whilst it's not up to date :(

**Comment by dhensby** [comment]
basically it needs to be PSR-2 compliant

**Comment by jeffreyguo** [comment]
Sorry, I just realised I did it in a forked repo.
Now I have rebased it from origin master, please check the new commit [2b21b06].

Cheers,
Jeffrey

**Comment by dhensby** [comment]
@tractorcow oh god of travis issues, any clues on this one?

**Comment by dhensby** [comment]
@jeffreyguo please can you address the issues in [Scrutinizer](https://scrutinizer-ci.com/g/silverstripe-labs/silverstripe-testsession/inspections/d409992f-475e-413d-b708-d7324eb03507/issues/files/code/TestSessionEnvironment.php?status=new&orderField=path&order=asc&honorSelectedPaths=0)

**Comment by assertchris** [comment]
@dhensby the PHP 5.4 test is testing master, which requires PHP 5.5 at least.

**Comment by dhensby** [comment]
@assertchris ok - shall I just delete that build from `.travis.yml` or should we move it to test against 3 branch?

**Comment by assertchris** [comment]
@dhensby I think the best would be that we test `5.3`, `5.4`, `5.5`, `5.6` against `3.2`, `5.6` against `3`, `3.1`, `master` and forget everything else.

**Comment by dhensby** [comment]
@assertchris ok, sure - can you make that happen?

**Comment by jeffreyguo** [comment]
@assertchris , @dhensby , could you help on this PR and merge it quickly? We need it to clean up test databases in TeamCity automatically as they consume disk resources a lot.
Thanks!

**Comment by dhensby** [comment]
the tests pass on the right branches. @jeffreyguo I think you just needed to rebase

**Pull request merged**
